---
##
# Bash improvements: bash history
##
- name: BLOCKINFILE | Extend history size / length
  blockinfile:
    path: "{{ bash_improve_global_bashrc }}"
    marker_begin: "Begin"
    marker_end: "End"
    marker: "# {mark} ansible: Extend the history size / length"
    block: |
      HISTFILESIZE={{ bash_improve_history_file_size }}
      HISTSIZE={{ bash_improve_history_memory_size }}
  when: bash_improve_history
  notify: enable user bashrc
