---
##
# Bash improvements: bash completion
##
- name: APT | Add bash completion package
  apt:
    name: "{{ bash_improve_bash_completion_package }}"
    state: present
  when: bash_improve_completion

- name: BLOCKINFILE | Enable bash completion for interactive shells
  blockinfile:
    path: "{{ bash_improve_global_bashrc }}"
    marker_begin: "Begin"
    marker_end: "End"
    marker: "# {mark} ansible: Enable bash completion for interactive shells"
    block: |
      if ! shopt -oq posix; then
        if [ -f /usr/share/bash-completion/bash_completion ]; then
          . /usr/share/bash-completion/bash_completion
        elif [ -f /etc/bash_completion ]; then
          . /etc/bash_completion
        fi
      fi
  when: bash_improve_completion
  notify: enable user bashrc
